use std::collections::BTreeMap;
use std::path::Path;

use super::handler::{HandlerArgs, InitHandler, InitOutput};
use crate::tree::TreeConfig;

/// Handler for `tree` — generates token-optimized directory tree markdown.
///
/// Replaces the old `archidoc tree` command.
/// Supports `--files`, `--human`, `--both`, `--depth N` flags via HandlerArgs.
pub struct TreeHandler;

impl InitHandler for TreeHandler {
    fn name(&self) -> &str {
        "tree"
    }

    fn description(&self) -> &str {
        "Generate token-optimized directory tree (was: tree). Flags: --files, --human, --both, --depth N"
    }

    fn generate(
        &self,
        target_dir: &Path,
        _vars: &BTreeMap<String, String>,
        extra_args: &HandlerArgs,
    ) -> Result<Vec<InitOutput>, String> {
        if !target_dir.exists() {
            return Err(format!("path does not exist: {}", target_dir.display()));
        }

        let config = TreeConfig::load(target_dir);
        let out_dir = extra_args
            .out
            .clone()
            .unwrap_or_else(|| target_dir.join("_context"));

        let emit_dirs = !extra_args.files || extra_args.both;
        let emit_files = extra_args.files || extra_args.both;

        let mut outputs = Vec::new();

        if emit_dirs {
            let content = format!(
                "# Directory Tree\n\n> Auto-generated by archidoc. Do not edit manually.\n\n```\n{}```\n",
                crate::tree::compact_dirs_tree(target_dir, extra_args.depth, &config)
            );
            outputs.push(InitOutput {
                path: out_dir.join("ARCHITECTURE.ai.tree.md"),
                contents: content,
            });
        }

        if emit_files {
            let content = format!(
                "# File Tree\n\n> Auto-generated by archidoc. Do not edit manually.\n\n```\n{}```\n",
                crate::tree::compact_files_tree(target_dir, extra_args.depth, &config)
            );
            outputs.push(InitOutput {
                path: out_dir.join("ARCHITECTURE.ai.files.md"),
                contents: content,
            });
        }

        if extra_args.human {
            let root_name = target_dir
                .file_name()
                .and_then(|n| n.to_str())
                .unwrap_or(".");
            let content = format!(
                "# Directory Tree — {}\n\n> Auto-generated by archidoc. Do not edit manually.\n\n{}\n",
                root_name,
                crate::tree::compact_human_tree(target_dir, extra_args.depth, &config)
            );
            outputs.push(InitOutput {
                path: out_dir.join("ARCHITECTURE.tree.md"),
                contents: content,
            });
        }

        Ok(outputs)
    }
}
