use std::path::Path;

use archidoc_types::ir::{ArchitectureIR, DirNode};
use archidoc_types::{C4Level, HealthStatus};

/// Generate the full ARCHITECTURE.md content as a string.
///
/// Sections:
/// 1. Header + narrative (from root node content)
/// 2. System Diagram (inline Mermaid C4 container)
/// 3. Component Diagram (inline Mermaid C4 component, if any)
/// 4. Component Index (table with source file links)
/// 5. Relationship Map
/// 6. Footer
pub fn generate(ir: &ArchitectureIR, columns: &[String]) -> String {
    let root = Path::new(&ir.scan_root);
    let annotated = ir.annotated_dirs();

    let mut output = String::new();

    output.push_str("# Architecture Context\n\n");
    output.push_str("> Auto-generated by archidoc. Do not edit manually.\n\n");

    output.push_str(&section_narrative(ir));
    output.push_str(&section_container_diagram(ir));
    output.push_str(&section_component_diagram(ir));
    output.push_str(&section_component_index(&annotated, root, &ir.scan_root, columns));
    output.push_str(&section_relationship_map(&annotated));

    output.push_str("---\n\n*Auto-generated by archidoc. Do not edit manually.*\n");

    output
}

/// Extract narrative prose from the root node's content.
///
/// Filters out @c4 markers, file table rows, and GoF lines.
fn section_narrative(ir: &ArchitectureIR) -> String {
    let content = match &ir.root.content {
        Some(c) => c,
        None => return String::new(),
    };
    // Only emit narrative if root is annotated
    if !ir.root.is_annotated() {
        return String::new();
    }

    let mut lines: Vec<&str> = Vec::new();
    let mut in_table = false;

    for line in content.lines() {
        let trimmed = line.trim();

        // Skip @c4 marker lines
        if trimmed.starts_with("@c4 ") {
            continue;
        }

        // Skip GoF lines
        if trimmed.starts_with("GoF:") {
            continue;
        }

        // Skip file table blocks
        if trimmed.starts_with("| File") || trimmed.starts_with("| file") {
            in_table = true;
            continue;
        }
        if in_table {
            if trimmed.starts_with('|') {
                continue;
            }
            in_table = false;
        }

        lines.push(line);
    }

    let narrative = lines.join("\n").trim().to_string();
    if narrative.is_empty() {
        String::new()
    } else {
        format!("{}\n\n", narrative)
    }
}

/// Inline Mermaid C4 container diagram.
fn section_container_diagram(ir: &ArchitectureIR) -> String {
    let has_containers = ir
        .annotated_dirs()
        .iter()
        .any(|d| d.c4_level == Some(C4Level::Container));
    if !has_containers {
        return String::new();
    }

    let diagram = crate::mermaid::container_diagram(ir);
    format!("## System Diagram\n\n{}\n\n", diagram)
}

/// Inline Mermaid C4 component diagram (skipped if no components).
fn section_component_diagram(ir: &ArchitectureIR) -> String {
    let has_components = ir
        .annotated_dirs()
        .iter()
        .any(|d| d.c4_level == Some(C4Level::Component));
    if !has_components {
        return String::new();
    }

    let diagram = crate::mermaid::component_diagram(ir);
    format!("## Component Diagram\n\n{}\n\n", diagram)
}

/// Component index table with links to source files.
///
/// `columns` overrides which columns appear. When empty, uses defaults:
/// `["Module", "Level", "Pattern", "Description"]`.
///
/// Recognized column names (case-insensitive):
/// - `Module` — module path as a hyperlink to source file
/// - `Level` — C4 level (container / component)
/// - `Pattern` — GoF pattern name
/// - `Description` — one-line module description
/// - `Source` — source file path (no hyperlink)
/// - `Parent` — parent container module path
/// - `Health` — file health summary (stable / active / planned counts)
/// - Unknown names render as `--`
fn section_component_index(
    annotated: &[&DirNode],
    root: &Path,
    scan_root: &str,
    columns: &[String],
) -> String {
    // Skip root node (path == ".") — equivalent to filtering out _lib
    let mut modules: Vec<&DirNode> = annotated
        .iter()
        .copied()
        .filter(|d| d.path != ".")
        .collect();
    modules.sort_by(|a, b| a.path.cmp(&b.path));

    if modules.is_empty() {
        return String::new();
    }

    let default_cols = vec![
        "Module".to_string(),
        "Level".to_string(),
        "Pattern".to_string(),
        "Description".to_string(),
    ];
    let cols: &[String] = if columns.is_empty() { &default_cols } else { columns };

    let separator: String = cols.iter().map(|_| "---").collect::<Vec<_>>().join("|");

    let mut output = String::new();
    output.push_str("## Component Index\n\n");
    output.push_str(&format!("| {} |\n", cols.join(" | ")));
    output.push_str(&format!("|{}|\n", separator));

    for dir in &modules {
        let cells: Vec<String> = cols
            .iter()
            .map(|col| resolve_column(col, dir, root, scan_root))
            .collect();
        output.push_str(&format!("| {} |\n", cells.join(" | ")));
    }

    output.push('\n');
    output
}

type ColumnResolver = fn(&DirNode, &Path, &str) -> String;

/// Dispatch table mapping column names to resolver functions.
const COLUMN_RESOLVERS: &[(&str, ColumnResolver)] = &[
    ("module", col_module),
    ("level", col_level),
    ("pattern", col_pattern),
    ("description", col_description),
    ("source", col_source),
    ("parent", col_parent),
    ("health", col_health),
];

fn col_module(dir: &DirNode, root: &Path, scan_root: &str) -> String {
    let source_path = resolve_source_path(dir, scan_root);
    let source = Path::new(&source_path);
    let rel = pathdiff::diff_paths(source, root)
        .unwrap_or_else(|| source.to_path_buf());
    // Display path uses dot-separated module_path style for backward compat
    let display_path = dir.path.replace('/', ".");
    format!(
        "[{}]({})",
        display_path,
        rel.display().to_string().replace('\\', "/")
    )
}

fn col_level(dir: &DirNode, _root: &Path, _scan_root: &str) -> String {
    dir.c4_level.unwrap_or(C4Level::Unknown).to_string()
}

fn col_pattern(dir: &DirNode, _root: &Path, _scan_root: &str) -> String {
    dir.pattern.as_deref().unwrap_or("--").to_string()
}

fn col_description(dir: &DirNode, _root: &Path, _scan_root: &str) -> String {
    dir.description.as_deref().unwrap_or("").to_string()
}

fn col_source(dir: &DirNode, root: &Path, scan_root: &str) -> String {
    let source_path = resolve_source_path(dir, scan_root);
    let source = Path::new(&source_path);
    let rel = pathdiff::diff_paths(source, root)
        .unwrap_or_else(|| source.to_path_buf());
    rel.display().to_string().replace('\\', "/")
}

fn col_parent(dir: &DirNode, _root: &Path, _scan_root: &str) -> String {
    match &dir.parent {
        Some(p) if p == "." => "_lib".to_string(),
        Some(p) => p.replace('/', "."),
        None => "--".to_string(),
    }
}

fn col_health(dir: &DirNode, _root: &Path, _scan_root: &str) -> String {
    let attributed_files: Vec<_> = dir.files.iter().filter(|f| f.health.is_some()).collect();
    if attributed_files.is_empty() {
        return "--".to_string();
    }
    let stable = attributed_files.iter().filter(|f| f.health == Some(HealthStatus::Stable)).count();
    let active = attributed_files.iter().filter(|f| f.health == Some(HealthStatus::Active)).count();
    let planned = attributed_files.iter().filter(|f| f.health == Some(HealthStatus::Planned)).count();
    format!("{} stable / {} active / {} planned", stable, active, planned)
}

/// Resolve a column name to its string value for a given DirNode.
fn resolve_column(col: &str, dir: &DirNode, root: &Path, scan_root: &str) -> String {
    let lower = col.to_lowercase();
    COLUMN_RESOLVERS
        .iter()
        .find(|(name, _)| *name == lower.as_str())
        .map(|(_, f)| f(dir, root, scan_root))
        .unwrap_or_else(|| "--".to_string())
}

/// Reconstruct an absolute source file path from a DirNode.
fn resolve_source_path(dir: &DirNode, scan_root: &str) -> String {
    match &dir.source_file {
        Some(rel) => {
            let root = Path::new(scan_root);
            let native_rel = rel.replace('/', std::path::MAIN_SEPARATOR_STR);
            root.join(native_rel).to_string_lossy().to_string()
        }
        None => String::new(),
    }
}

/// Flat relationship map across all modules.
fn section_relationship_map(annotated: &[&DirNode]) -> String {
    let all_rels: Vec<(&str, &archidoc_types::ir::Relationship)> = annotated
        .iter()
        .flat_map(|dir| {
            dir.relationships
                .iter()
                .map(move |r| (dir.path.as_str(), r))
        })
        .collect();

    if all_rels.is_empty() {
        return String::new();
    }

    let mut output = String::new();
    output.push_str("## Relationship Map\n\n");

    for (source, rel) in &all_rels {
        // Display source path as dot-separated for backward compat
        let display_source = source.replace('/', ".");
        output.push_str(&format!(
            "- {} -> {}: \"{}\" ({})\n",
            display_source, rel.target, rel.label, rel.protocol
        ));
    }

    output.push('\n');
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use archidoc_types::ir::{ArchitectureIR, DirNode, Relationship};
    use archidoc_types::C4Level;

    fn make_ir_with_dirs(dirs: Vec<DirNode>, root_content: Option<String>) -> ArchitectureIR {
        let mut root = DirNode::empty(".", ".");
        if root_content.is_some() {
            root.c4_level = Some(C4Level::Container);
            root.content = root_content;
        }
        root.dirs = dirs;
        ArchitectureIR {
            version: "2.0".to_string(),
            scan_root: String::new(),
            root,
        }
    }

    fn make_container_dir(name: &str, desc: &str) -> DirNode {
        let mut dir = DirNode::empty(name, name);
        dir.c4_level = Some(C4Level::Container);
        dir.description = Some(desc.to_string());
        dir.source_file = Some(format!("{}/mod.rs", name));
        dir
    }

    fn make_component_dir(parent: &str, name: &str, desc: &str) -> DirNode {
        let path = format!("{}/{}", parent, name);
        let mut dir = DirNode::empty(name, &path);
        dir.c4_level = Some(C4Level::Component);
        dir.description = Some(desc.to_string());
        dir.source_file = Some(format!("{}/{}/mod.rs", parent, name));
        dir.parent = Some(parent.to_string());
        dir
    }

    #[test]
    fn empty_docs_produces_header_and_footer() {
        let ir = make_ir_with_dirs(vec![], None);
        let output = generate(&ir, &[]);
        assert!(output.contains("# Architecture Context"));
        assert!(output.contains("Auto-generated by archidoc"));
        assert!(!output.contains("## System Diagram"));
        assert!(!output.contains("## Component Index"));
    }

    #[test]
    fn single_container_produces_diagram_and_index() {
        let ir = make_ir_with_dirs(vec![make_container_dir("api", "REST API gateway")], None);
        let output = generate(&ir, &[]);

        assert!(output.contains("## System Diagram"));
        assert!(output.contains("```mermaid"));
        assert!(output.contains("Container(api"));
        assert!(output.contains("## Component Index"));
        assert!(output.contains("| [api](api/mod.rs) | container | -- | REST API gateway |"));
    }

    #[test]
    fn components_produce_component_diagram() {
        let mut bus = make_container_dir("bus", "Central messaging");
        bus.dirs.push(make_component_dir("bus", "calc", "Indicator calculations"));
        let ir = make_ir_with_dirs(vec![bus], None);
        let output = generate(&ir, &[]);

        assert!(output.contains("## Component Diagram"));
        assert!(output.contains("C4Component"));
        assert!(output.contains("Component(bus_calc"));
    }

    #[test]
    fn no_component_diagram_when_no_components() {
        let ir = make_ir_with_dirs(vec![make_container_dir("api", "REST API")], None);
        let output = generate(&ir, &[]);

        assert!(!output.contains("## Component Diagram"));
    }

    #[test]
    fn relationships_appear_in_map() {
        let mut api = make_container_dir("api", "REST API gateway");
        api.relationships = vec![Relationship {
            target: "database".to_string(),
            label: "Persists data".to_string(),
            protocol: "sqlx".to_string(),
        }];

        let ir = make_ir_with_dirs(vec![api, make_container_dir("database", "Data store")], None);
        let output = generate(&ir, &[]);

        assert!(output.contains("## Relationship Map"));
        assert!(output.contains("- api -> database: \"Persists data\" (sqlx)"));
    }

    #[test]
    fn narrative_extracted_from_root() {
        let ir = make_ir_with_dirs(
            vec![make_container_dir("api", "REST API")],
            Some("@c4 container\n\n# My Project\n\nA cool project.\n\n## Data Flow\n\n1. Step one\n2. Step two".to_string()),
        );
        let output = generate(&ir, &[]);

        assert!(output.contains("# My Project"));
        assert!(output.contains("A cool project."));
        assert!(output.contains("## Data Flow"));
        assert!(output.contains("1. Step one"));
        assert!(!output.contains("@c4 container"));
    }

    #[test]
    fn narrative_filters_file_tables() {
        let ir = make_ir_with_dirs(
            vec![],
            Some("@c4 container\n\n# Engine\n\nCore system.\n\n| File | Pattern | Purpose | Health |\n|------|---------|---------|--------|\n| `core.rs` | Facade | Entry point | stable |\n\nGoF: Mediator".to_string()),
        );
        let output = generate(&ir, &[]);

        assert!(output.contains("Core system."));
        assert!(!output.contains("| File |"));
        assert!(!output.contains("core.rs"));
        assert!(!output.contains("GoF:"));
    }

    #[test]
    fn index_links_use_forward_slashes() {
        let mut dir = make_container_dir("api", "REST API");
        dir.source_file = Some("api\\mod.rs".to_string());
        let ir = make_ir_with_dirs(vec![dir], None);
        let output = generate(&ir, &[]);

        assert!(output.contains("[api](api/mod.rs)"));
    }

    #[test]
    fn lib_module_excluded_from_index() {
        let ir = make_ir_with_dirs(
            vec![make_container_dir("api", "REST API")],
            Some("# Root\n\nNarrative.".to_string()),
        );
        // root is annotated via make_ir_with_dirs
        let output = generate(&ir, &[]);

        // root (path=".") should NOT appear in component index
        assert!(!output.contains("| [.]"));
        assert!(!output.contains("| [_lib]"));
        // api should appear
        assert!(output.contains("| [api]"));
    }
}
